---
layout: cv
title: Lucy Barney Olaveson's CV
---
# Lucy Barney Olaveson
Bachelor of Science in Accounting Student, Data Science Minor

<div id="webaddress">
<a href="isaac@applesdofall.org">isaac@applesdofall.org</a>
| <a href="http://en.wikipedia.org/wiki/Isaac_Newton">My wikipedia page</a>
</div>


## Currently

Obtaining undergraduate degree at Brigham Young University - Idaho

### Specialized in

Financial Accounting, SQL, Excel, Python


### Research interests

Financial planning, utilizing business efficiency, financial planning


## Education

`2025 - now`
__Brigham Young University - Idaho__

`2024 - 2025`
__Utah State University__

`2022 - 2024`
__College of Southern Idaho__




## Awards

`2024`
National Champion - National FFA Equine Science 1st Place





## Publications

National FFA New Horizons Magazine [Lucy Barney's Numerous Accomplishments](https://www.ffa.org/the-feed/lessons-learned-from-an-award-winning-sae/)

Pacific Ag NorthWest Radio Article [PANW](https://pnwag.net/idahos-lucy-barney-national-winner-at-national-ffa-convention/)

<!-- A list is also available [online](http://scholar.google.co.uk/citations?user=LTOTl0YAAAAJ) -->

### Journals

`2025`
Special Learning [NGGYU](https://www.youtube.com/watch?v=dQw4w9WgXcQ)


## Occupation

`2019-2024`
__Sage Ridge Farms - Dog Breeding Program Business Owner__, Rigby, Idaho


`2020-2024`
__Barney Shires - Draft Horse Trainer__, Lewisville, Idaho



<!-- ### Footer

Last updated: December 2025 -->